In [38]:
import numpy as np

import tensorflow.keras
from tensorflow.keras.layers import Dense

## 2장 시작하기전에

**케라스의 층에서 일어나는 일**

In [40]:
keras.layers.Dense(512, activation = "relu")

이 함수를 구체적으로 살펴보면 다음과 같다

In [ ]:
output = relu(dot(W, input)+b)

여기서는 3개의 텐서 연산이 있다. 입력텐서와 텐서 W사이의 점곱(dot), 점곱의 결과인 2D텐서와 벡터 b 사이의 덧셈(+), 마지막으로 relu 연산이 있다.

### relu

relu 연산은 0보다 크면 해당 값을 리턴해주고 0보다 작으면 0을 리턴해주는 함수이다.

In [18]:
def naive_relu(x):
    assert len(x.shape)==2
    
    x = x.copy() # 입력 텐서 자체를 바꾸지 않도록 복사
    
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] = max(x[i, j], 0)
    
    return x

assert : 실행하기 전 조건을 체크하는 가정 설정문

In [22]:
sample = np.random.randn(100)
sample = sample.reshape(5,-1)

In [33]:
naive_relu(sample)

array([[0.58521872, 2.25782806, 0.74308367, 0.        , 0.2580674 ,
        1.56777564, 0.        , 0.        , 1.22076248, 0.        ,
        1.08383981, 0.30334784, 0.        , 3.40345259, 1.06624647,
        0.4440177 , 0.39372728, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.28542368, 0.        , 0.        , 0.29372707, 2.42939952,
        0.        , 0.        , 0.        , 0.        , 1.10708034,
        1.13572845, 0.73980583, 0.9085446 , 0.        , 0.59096656],
       [0.        , 0.07568914, 0.        , 0.        , 1.59959272,
        0.        , 0.14606314, 0.41908409, 1.35499087, 0.7314253 ,
        0.1832957 , 1.62558245, 0.42297293, 0.        , 0.        ,
        0.56138018, 0.31812999, 0.6975283 , 0.        , 0.        ],
       [0.49817498, 0.        , 0.        , 0.        , 0.79880903,
        1.07835002, 0.        , 0.        , 0.17772686, 0.        ,
        0.47236855, 0.11623342, 1.17924344, 0

relu 함수 실행결과를 보면 0보다 작은 값은 없는 것을 확인할 수 있다.

### 덧셈

In [42]:
def naive_add(x,y):
    assert len(x.shape)==2 # 2D 텐서가 아니면 실행x
    assert x.shape == y.shape
    
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

In [43]:
sample2 = np.random.randn(100).reshape(5,-1)

In [49]:
sample[0], sample2[0]

(array([ 0.58521872,  2.25782806,  0.74308367, -2.23047349,  0.2580674 ,
         1.56777564, -0.10597576, -0.13588714,  1.22076248, -0.25468999,
         1.08383981,  0.30334784, -1.95331606,  3.40345259,  1.06624647,
         0.4440177 ,  0.39372728, -0.99133837, -1.6769636 , -0.32846341]),
 array([-0.78966345,  0.53178311,  1.36346126,  0.29140191,  1.02674698,
         1.27306082, -0.61392197, -0.46649167,  1.7412095 , -1.39410855,
        -0.13982356,  0.90762863, -0.95906655, -0.39049353, -0.62998502,
        -0.61360755, -1.03660082,  1.06040888, -0.61081174, -0.22305455]))

In [46]:
naive_add(sample, sample2)

array([[-0.20444473,  2.78961117,  2.10654493, -1.93907158,  1.28481438,
         2.84083646, -0.71989773, -0.60237881,  2.96197198, -1.64879854,
         0.94401625,  1.21097646, -2.91238261,  3.01295906,  0.43626145,
        -0.16958985, -0.64287354,  0.06907051, -2.28777534, -0.55151796],
       [ 1.26130443, -0.94886311, -1.67972058, -3.88010185,  0.17618523,
         3.45033145,  2.02924995, -0.5592356 , -0.50592866,  2.22505017,
         0.58420986,  0.97327954, -0.3050229 , -1.24564739, -0.14983954,
         1.76911332,  0.50609146,  1.11862943, -1.38486452,  2.05310262],
       [-2.12859953,  0.27627377, -1.3823682 , -0.74205121,  1.56895723,
        -1.38438028,  1.02528033,  2.62491206,  1.85452236,  0.31184377,
         1.64526966,  0.91708661,  1.28205645,  0.61195712,  0.57696113,
         1.24587252, -0.62587205,  0.9004573 , -0.22502829, -0.40046108],
       [ 0.89702743,  0.05590668, -0.86602396, -0.71189963,  0.24668496,
        -0.15460237, -1.6185873 , -1.23434118, -

sample과 sample2의 원소가 합쳐진 것을 확인할 수 있다.

#### 넘파이의 특징

- 넘파이는 배열을 다룰 떄는 최적화된 넘파이 내장 함수로 이런 연산들을 처리할 수 있다.

  넘파이는 시스템내에 설치된 BLAS(Basic Linear Algebra Subprogram) 구현에 복잡한 일들을 위임한다.

  BLAS는 고도로 병렬화되고 효율적인 저수준의 텐서 조작 루틴이며, 포트란이나 C언어로 구현되어 있다.

  그래서 넘파이는 원소별 연산을 엄청난 속도로 처리한다.

In [50]:
# example

z = sample + sample2 # 원소별 덧셈
z = np.maximum(z,0.) # relu 함수

### Broad Casting

2D 텐서와 벡터간의 연산은 어떻게 진행될까?

1. 큰 텐서의 ndim에 맞도록 작은 텐서에 (브로드캐스팅 축이라고 부르는)축이 추가된다.
2. 작은 텐서가 새 축을 따라서 큰 텐서의 크기에 맞도록 반복된다.

In [53]:
# example
x = np.random.randn(320).reshape(32,10) # 2D 텐서
y = np.random.randn(10) # 벡터

In [59]:
def naive_add_matrix_and_vector(x, y):
    assert len(x.shape) == 2 # x는 2D 넘파이 배열
    assert len(y.shape) == 1 # y는 넘파이 벡터
    assert x.shape[1] == y.shape[0]
    
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[j]
            
    return x

x의 각 행에 y가 추가 되며 이 과정을 32번을 반복하게 된다.

크기가 다른 두 테서에 브로드캐스팅으로 원소별 maximum 연산을 적용하는 예

In [61]:
x = np.random.random((64,3,32,10)) # x는 (64,3,32,10) 크기의 랜덤 텐서
y = np.random.random((32,10)) # y는 (32,10) 크기의 랜덤 텐서

z = np.maximum(x, y)

In [66]:
x[0][0][0]

array([0.69289568, 0.14360401, 0.23753031, 0.78157018, 0.4341446 ,
       0.64237859, 0.0792176 , 0.0971101 , 0.70420593, 0.04048192])

In [69]:
y[0]

array([0.82302012, 0.18630778, 0.00421223, 0.59571485, 0.85371041,
       0.87898359, 0.65536461, 0.69715674, 0.96066126, 0.19431836])

In [72]:
z[0][0][0]

array([0.82302012, 0.18630778, 0.23753031, 0.78157018, 0.85371041,
       0.87898359, 0.65536461, 0.69715674, 0.96066126, 0.19431836])

### 텐서 점곱

In [74]:
def naive_vector_dot(x,y):
    assert len(x.shape)==1
    assert len(y.shape)==1
    assert x.shape[0]==y.shape[0]
    
    z = 0.
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z

In [75]:
x = np.random.randn(4)
y = np.random.randn(4)

In [76]:
x, y

(array([-0.70463715, -0.0328315 ,  0.2170684 ,  0.08401227]),
 array([-0.89455023,  0.46318722, -0.11781573,  0.75780719]))

In [77]:
naive_vector_dot(x,y) # 결과가 스칼라가 됨

0.6532172187638776

두 벡터의 점곱은 스칼라가 되므로 원소 개수가 같은 벡터끼리 점곱이 가능하다.

행렬과 벡터 사이에서도 점곱이 가능하다.

y와 x의 행 사이에서 점곱이 일어나므로 벡터가 반환된다.

In [79]:
def naive_matrix_vector_dot(x,y):
    assert len(x.shape)==2
    assert len(y.shape)==1
    assert x.shape[1] == y.shape[0]
    
    z = np.zeros(x.shape[0]) # x의 행과 같은 크기의 0이 채워진 벡터를 만듬
    
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i] += x[i, j] * y[j]

    return z

In [80]:
x = np.random.random((3,4))
y = np.random.randn(4)

In [81]:
x, y

(array([[0.15027946, 0.02822771, 0.01123323, 0.66133556],
        [0.66514075, 0.00733225, 0.87835893, 0.41049886],
        [0.37592826, 0.15672708, 0.23799372, 0.94949961]]),
 array([-1.338573  , -0.13545497, -0.86139207,  0.11669829]))

In [82]:
naive_matrix_vector_dot(x,y)

array([-0.1374831 , -1.60003954, -0.61863781])

(3 * 4) x (4 * 1 ) 행렬 곱이라 생각하면 된다.

벡터-벡터의 점곱은 교환 법칙이 성립하지만 **행렬-벡터 점곱은 교환 법칙이 성립하지 않는다!**

#### 행렬-행렬의 점곱

In [92]:
x = np.random.random((3,2))
y = np.random.random((2,3))

In [95]:
def naive_matrix_dot(x,y):
    assert len(x.shape)==2
    assert len(y.shape)==2
    assert x.shape[1]==y.shape[0]
    
    z = np.zeros((x.shape[0],y.shape[1]))
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            row_x = x[i, :]
            column_y = y[:, j]
            z[i, j] = naive_vector_dot(row_x,column_y)
    return z

In [98]:
naive_matrix_dot(x,y).shape

(3, 3)