In [1]:
# 표준화 : 평균 0, 표준편차 1인 표준 정규분포

# 1) 표준화 = (각 데이터 - 평균값) / 표준편차
# 2) zscore()
# 3) fit_transform()

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
data = np.random.randint(30, size=(6,5))
data

array([[ 9,  6,  8, 12,  4],
       [15, 24, 28,  5, 29],
       [10, 10,  2, 21, 12],
       [27, 13,  0, 18, 17],
       [26, 20, 17, 15,  3],
       [14, 26,  1, 19, 13]])

In [47]:
(9-np.mean(data))

-5.133333333333333

In [4]:
# 6행 5열, 각 열 단위로 표준화 작업을 진행하고 출력

In [38]:
np.mean(data, axis = 0) # axis=0 : 열 기준
data.mean(axis = 0)

np.mean(data, axis = 1) # 행기준

array([ 7.8, 20.2, 11. , 15. , 16.2, 14.6])

In [42]:
data_s1 = (data - np.mean(data, axis = 0 )) / np.std(data, axis = 0)
data_s1

array([[-1.09539553, -1.42997282, -0.13123574, -0.56360186, -1.03464225],
       [-0.25636917,  1.02140915,  1.8373004 , -1.87867287,  1.839364  ],
       [-0.9555578 , -0.88522127, -0.72179659,  1.12720372, -0.11496025],
       [ 1.42168356, -0.47665761, -0.9186502 ,  0.56360186,  0.459841  ],
       [ 1.28184583,  0.47665761,  0.75460552,  0.        , -1.1496025 ],
       [-0.39620689,  1.29378493, -0.82022339,  0.75146915,  0.        ]])

In [41]:
import scipy.stats as ss

In [44]:
data_s2 = ss.zscore(data)
data_s2

array([[-1.09539553, -1.42997282, -0.13123574, -0.56360186, -1.03464225],
       [-0.25636917,  1.02140915,  1.8373004 , -1.87867287,  1.839364  ],
       [-0.9555578 , -0.88522127, -0.72179659,  1.12720372, -0.11496025],
       [ 1.42168356, -0.47665761, -0.9186502 ,  0.56360186,  0.459841  ],
       [ 1.28184583,  0.47665761,  0.75460552,  0.        , -1.1496025 ],
       [-0.39620689,  1.29378493, -0.82022339,  0.75146915,  0.        ]])

In [48]:
from sklearn.preprocessing import StandardScaler

In [50]:
data_s3 = StandardScaler().fit_transform(data)
data_s3

array([[-1.09539553, -1.42997282, -0.13123574, -0.56360186, -1.03464225],
       [-0.25636917,  1.02140915,  1.8373004 , -1.87867287,  1.839364  ],
       [-0.9555578 , -0.88522127, -0.72179659,  1.12720372, -0.11496025],
       [ 1.42168356, -0.47665761, -0.9186502 ,  0.56360186,  0.459841  ],
       [ 1.28184583,  0.47665761,  0.75460552,  0.        , -1.1496025 ],
       [-0.39620689,  1.29378493, -0.82022339,  0.75146915,  0.        ]])

In [53]:
# 평균보다 이상치에 덜 민감한 중앙값을 사용하는걸 고려 => 이상치(극단적인 값)가 평균에 영향을 끼치기 때문에

from sklearn.preprocessing import RobustScaler
# RobustScaler는 기존의 표준화방법의 문제점인 평균, 표준편차는
# 특이값으로부터 영향을 많이 받게 됨 -> 표준화 결과가 왜곡
# RobustScaler로 표준화 = (각 데이터 - 중앙값) / IQR

In [56]:
# 사용법
RobustScaler().fit_transform(data)

array([[-0.44897959, -0.85714286,  0.22222222, -0.75      , -0.85      ],
       [ 0.04081633,  0.6122449 ,  1.7037037 , -1.91666667,  1.65      ],
       [-0.36734694, -0.53061224, -0.22222222,  0.75      , -0.05      ],
       [ 1.02040816, -0.28571429, -0.37037037,  0.25      ,  0.45      ],
       [ 0.93877551,  0.28571429,  0.88888889, -0.25      , -0.95      ],
       [-0.04081633,  0.7755102 , -0.2962963 ,  0.41666667,  0.05      ]])

In [58]:
from sklearn.preprocessing import MinMaxScaler, minmax_scale

# MinMaxScaler, minmax_scale : 0 ~ 1 사이의 값으로 스케일링

In [59]:
data

array([[ 9,  6,  8, 12,  4],
       [15, 24, 28,  5, 29],
       [10, 10,  2, 21, 12],
       [27, 13,  0, 18, 17],
       [26, 20, 17, 15,  3],
       [14, 26,  1, 19, 13]])

In [63]:
data.min(axis = 0)

array([9, 6, 0, 5, 3])

In [67]:
data_m1 = (data - data.min(axis = 0)) / (data.max(axis= 0) - data.min(axis=0))
data_m1

array([[0.        , 0.        , 0.28571429, 0.4375    , 0.03846154],
       [0.33333333, 0.9       , 1.        , 0.        , 1.        ],
       [0.05555556, 0.2       , 0.07142857, 1.        , 0.34615385],
       [1.        , 0.35      , 0.        , 0.8125    , 0.53846154],
       [0.94444444, 0.7       , 0.60714286, 0.625     , 0.        ],
       [0.27777778, 1.        , 0.03571429, 0.875     , 0.38461538]])

In [69]:
data_m2 = MinMaxScaler().fit_transform(data)
data_m2

array([[0.        , 0.        , 0.28571429, 0.4375    , 0.03846154],
       [0.33333333, 0.9       , 1.        , 0.        , 1.        ],
       [0.05555556, 0.2       , 0.07142857, 1.        , 0.34615385],
       [1.        , 0.35      , 0.        , 0.8125    , 0.53846154],
       [0.94444444, 0.7       , 0.60714286, 0.625     , 0.        ],
       [0.27777778, 1.        , 0.03571429, 0.875     , 0.38461538]])

In [ ]:
# 왜 열을 기준으로 계산할까??

In [70]:
# 이진화
# 연속형 변수값 -> 기준에 따라 -> 0 또는 1로 이진화
# 베르누이 시행(성공/실패)
# 성공확률이 p인 베르누이 시행을 n번 반복했을 때,
# 성공횟수를 x라고 한다면,
# 확률변수 x는 n과 p인 이항분포를 따른다.

In [71]:
data

array([[ 9,  6,  8, 12,  4],
       [15, 24, 28,  5, 29],
       [10, 10,  2, 21, 12],
       [27, 13,  0, 18, 17],
       [26, 20, 17, 15,  3],
       [14, 26,  1, 19, 13]])

In [73]:
# 이산화(이항변수화)
from sklearn.preprocessing import Binarizer

In [79]:
binarizer = Binarizer().fit(data)
binarizer.transform(data)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 0, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [89]:
help(Binarizer())

Help on Binarizer in module sklearn.preprocessing._data object:

class Binarizer(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
 |  Binarizer(*, threshold=0.0, copy=True)
 |  
 |  Binarize data (set feature values to 0 or 1) according to a threshold.
 |  
 |  Values greater than the threshold map to 1, while values less than
 |  or equal to the threshold map to 0. With the default threshold of 0,
 |  only positive values map to 1.
 |  
 |  Binarization is a common operation on text count data where the
 |  analyst can decide to only consider the presence or absence of a
 |  feature rather than a quantified number of occurrences for instance.
 |  
 |  It can also be used as a pre-processing step for estimators that
 |  consider boolean random variables (e.g. modelled using the Bernoulli
 |  distribution in a Bayesian setting).
 |  
 |  Read more in the :ref:`User Guide <preprocessing_binarization>`.
 |  
 |  Parameters
 |  ----------
 |  threshold : float, default=0.0
 |    

In [83]:
# Binarizer(threshold 값 지정) 객체 생성 후 이 객체기준으로 data를 이산화 만듦
b2 = Binarizer(threshold=15)
b2.transform(data)

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 1, 1],
       [1, 1, 1, 0, 0],
       [0, 1, 0, 1, 0]])

In [84]:
from sklearn.preprocessing import binarize

In [88]:
binarize(data, threshold=15)

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 1, 1],
       [1, 1, 1, 0, 0],
       [0, 1, 0, 1, 0]])

In [90]:
# OneHotEncoder
# Hot은 1을 의미함. 1개만 1이고 나머지는 0이 되도록 인코딩
# 범주형 -> 이산화

# ex) 성별(범주형) -> 0(남성) 또는 1(여성) -> 10 또는 01
#     연령대 -> 0(20대), 1(30대), 2(40대) -> 100 또는 010 또는 001
#     학점 -> A(0), B(1), C(2), D(3), F(4) -> 10000 01000 00100 00010 00001

In [ ]:
# 학생1 0(남성) 0(20대) 0(A) -> 원핫인코딩 -> 10 100 10000
# 학생2 0 1 1
# ...
# 학생n 1 1 4

In [91]:
from sklearn.preprocessing import OneHotEncoder

In [92]:
data = np.array([[0,0,0],
                 [0,1,1],
                 [1,2,2],
                 [1,1,4]])

In [93]:
# data -> 원핫인코딩

In [102]:
enc = OneHotEncoder() # OneHotEncoder 객체 생성
enc

OneHotEncoder()

In [103]:
enc.fit(data)

OneHotEncoder()

In [105]:
# enc.get_params()
# enc.get_feature_names()

array(['x0_0', 'x0_1', 'x1_0', 'x1_1', 'x1_2', 'x2_0', 'x2_1', 'x2_2',
       'x2_4'], dtype=object)

In [109]:
enc.transform(data).toarray()

array([[1., 0., 1., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 1.]])

In [110]:
df = pd.DataFrame({'C1': np.random.randn(20),
 'C2': ['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a','b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b']})
df

C1 C2
0   0.256565  a
1   0.371152  a
2  -1.225436  a
3  -0.161624  a
4  -0.548289  a
5  -0.106206  a
6   1.418957  a
7  -0.945064  a
8  -1.024221  a
9  -0.315997  a
10 -1.600255  b
11  0.747238  b
12 -0.509416  b
13 -0.052110  b
14  0.416724  b
15  0.354600  b
16 -1.088409  b
17  0.393040  b
18  1.540435  b
19 -1.668788  b

In [ ]:
c1열 값에 대해 구간을 나누고자 함
최소값 ~ 최대값을 5개 구간을 균등하게 나눔

In [117]:
df["C1"].min(), df["C1"].max()

(-1.6687876421478334, 1.540434570266129)

In [156]:
bins = np.linspace(df.C1.min(),df.C1.max(),5) # 균등구간
bins # 구간 설정

array([-1.66878764, -0.86648209, -0.06417654,  0.73812902,  1.54043457])

In [120]:
df["C1bin"] = np.digitize(df["C1"], bins) # 구간에 해당하는 숫자로 바꿔줌(1 ~ 5 구간)

In [ ]:
1: -1.66878764 ~ -0.86648209 사이에 속함
2: -0.86648209 ~ -0.06417654 사이에 속함
    ...
5: 1.54043457 마지막 값

In [121]:
df

C1 C2  C1bin
0   0.256565  a      3
1   0.371152  a      3
2  -1.225436  a      1
3  -0.161624  a      2
4  -0.548289  a      2
5  -0.106206  a      2
6   1.418957  a      4
7  -0.945064  a      1
8  -1.024221  a      1
9  -0.315997  a      2
10 -1.600255  b      1
11  0.747238  b      4
12 -0.509416  b      2
13 -0.052110  b      3
14  0.416724  b      3
15  0.354600  b      3
16 -1.088409  b      1
17  0.393040  b      3
18  1.540435  b      5
19 -1.668788  b      1

In [135]:
# groupby 객체 확인하기
df.groupby("C1bin").get_group(1) # 1번 그룹에 대한 정보

C1
C1bin          
1     -7.552172
2     -1.641532
3      1.739970
4      2.166195
5      1.540435

In [141]:
# 각 구간별 데이터 건수 출력

df.groupby("C1bin")["C2"].value_counts()
df.groupby("C1bin").size()
df.groupby("C1bin").count()

C1  C2
C1bin        
1       6   6
2       5   5
3       6   6
4       2   2
5       1   1

In [143]:
df["C1bin"] == 2

0     False
1     False
2     False
3      True
4      True
5      True
6     False
7     False
8     False
9      True
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: C1bin, dtype: bool

In [147]:
# df의 C1bin열에 대해 get_dummies사용
pd.get_dummies(df["C1bin"], prefix="C1") # prefix 사용시 해당열 인덱스가 컬럼으로 감

C1_1  C1_2  C1_3  C1_4  C1_5
0      0     0     1     0     0
1      0     0     1     0     0
2      1     0     0     0     0
3      0     1     0     0     0
4      0     1     0     0     0
5      0     1     0     0     0
6      0     0     0     1     0
7      1     0     0     0     0
8      1     0     0     0     0
9      0     1     0     0     0
10     1     0     0     0     0
11     0     0     0     1     0
12     0     1     0     0     0
13     0     0     1     0     0
14     0     0     1     0     0
15     0     0     1     0     0
16     1     0     0     0     0
17     0     0     1     0     0
18     0     0     0     0     1
19     1     0     0     0     0

In [148]:
df
# c1열 값 c1열 값의 평균보다 크면 => "high"
# else => "low"
# high_low열에 저장

C1 C2  C1bin
0   0.256565  a      3
1   0.371152  a      3
2  -1.225436  a      1
3  -0.161624  a      2
4  -0.548289  a      2
5  -0.106206  a      2
6   1.418957  a      4
7  -0.945064  a      1
8  -1.024221  a      1
9  -0.315997  a      2
10 -1.600255  b      1
11  0.747238  b      4
12 -0.509416  b      2
13 -0.052110  b      3
14  0.416724  b      3
15  0.354600  b      3
16 -1.088409  b      1
17  0.393040  b      3
18  1.540435  b      5
19 -1.668788  b      1

In [153]:
mean = df["C1"].mean()

In [154]:
high_low = []
mean = df["C1"].mean()
for c in df["C1"]:
    if c > mean:
        c = "high"
    else:
        c = "low"
    high_low.append(c)
df["high_low"] = high_low
df

C1 C2  C1bin high_low
0   0.256565  a      3     high
1   0.371152  a      3     high
2  -1.225436  a      1      low
3  -0.161624  a      2     high
4  -0.548289  a      2      low
5  -0.106206  a      2     high
6   1.418957  a      4     high
7  -0.945064  a      1      low
8  -1.024221  a      1      low
9  -0.315997  a      2      low
10 -1.600255  b      1      low
11  0.747238  b      4     high
12 -0.509416  b      2      low
13 -0.052110  b      3     high
14  0.416724  b      3     high
15  0.354600  b      3     high
16 -1.088409  b      1      low
17  0.393040  b      3     high
18  1.540435  b      5     high
19 -1.668788  b      1      low

In [157]:
df.C1.mean()

-0.1873552299568594

In [166]:
bins = np.linspace(df.C1.min(),df.C1.mean(),2)
bins

array([-1.66878764, -0.18735523])

In [171]:
high_low = []
bins = np.linspace(df.C1.min(),df.C1.mean(),2)
for i in np.digitize(df["C1"], bins):
    if i == 1:
        i = "low"
    else:
        i = "high"
    high_low.append(i)
df["high_low"] = high_low

C1 C2  C1bin high_low  highLow
0   0.256565  a      3     high        2
1   0.371152  a      3     high        2
2  -1.225436  a      1      low        1
3  -0.161624  a      2     high        2
4  -0.548289  a      2      low        1
5  -0.106206  a      2     high        2
6   1.418957  a      4     high        2
7  -0.945064  a      1      low        1
8  -1.024221  a      1      low        1
9  -0.315997  a      2      low        1
10 -1.600255  b      1      low        1
11  0.747238  b      4     high        2
12 -0.509416  b      2      low        1
13 -0.052110  b      3     high        2
14  0.416724  b      3     high        2
15  0.354600  b      3     high        2
16 -1.088409  b      1      low        1
17  0.393040  b      3     high        2
18  1.540435  b      5     high        2
19 -1.668788  b      1      low        1

In [176]:
df["high_low"] = binarize(df["C1"].values.reshape(-1,1),threshold=df["C1"].mean())
df["high_low"].replace({1:"high",0:"low"},inplace=True)
df

C1 C2  C1bin high_low  highLow
0   0.256565  a      3     high        2
1   0.371152  a      3     high        2
2  -1.225436  a      1      low        1
3  -0.161624  a      2     high        2
4  -0.548289  a      2      low        1
5  -0.106206  a      2     high        2
6   1.418957  a      4     high        2
7  -0.945064  a      1      low        1
8  -1.024221  a      1      low        1
9  -0.315997  a      2      low        1
10 -1.600255  b      1      low        1
11  0.747238  b      4     high        2
12 -0.509416  b      2      low        1
13 -0.052110  b      3     high        2
14  0.416724  b      3     high        2
15  0.354600  b      3     high        2
16 -1.088409  b      1      low        1
17  0.393040  b      3     high        2
18  1.540435  b      5     high        2
19 -1.668788  b      1      low        1

In [177]:
# np.where(조건, 참, 거짓)

df["high_low"] = np.where(df["C1"] > df["C1"].mean(), "high", "low")
df

C1 C2  C1bin high_low  highLow
0   0.256565  a      3     high        2
1   0.371152  a      3     high        2
2  -1.225436  a      1      low        1
3  -0.161624  a      2     high        2
4  -0.548289  a      2      low        1
5  -0.106206  a      2     high        2
6   1.418957  a      4     high        2
7  -0.945064  a      1      low        1
8  -1.024221  a      1      low        1
9  -0.315997  a      2      low        1
10 -1.600255  b      1      low        1
11  0.747238  b      4     high        2
12 -0.509416  b      2      low        1
13 -0.052110  b      3     high        2
14  0.416724  b      3     high        2
15  0.354600  b      3     high        2
16 -1.088409  b      1      low        1
17  0.393040  b      3     high        2
18  1.540435  b      5     high        2
19 -1.668788  b      1      low        1

In [179]:
df.groupby("high_low").size()
df.groupby("high_low")["C1"].mean()

high_low
high    0.470797
low    -0.991764
Name: C1, dtype: float64

In [180]:
df["high_low"] = np.where(df["C1"] > df["C1"].mean(), "high", "low")
df

C1 C2  C1bin high_low  highLow
0   0.256565  a      3     high        2
1   0.371152  a      3     high        2
2  -1.225436  a      1      low        1
3  -0.161624  a      2     high        2
4  -0.548289  a      2      low        1
5  -0.106206  a      2     high        2
6   1.418957  a      4     high        2
7  -0.945064  a      1      low        1
8  -1.024221  a      1      low        1
9  -0.315997  a      2      low        1
10 -1.600255  b      1      low        1
11  0.747238  b      4     high        2
12 -0.509416  b      2      low        1
13 -0.052110  b      3     high        2
14  0.416724  b      3     high        2
15  0.354600  b      3     high        2
16 -1.088409  b      1      low        1
17  0.393040  b      3     high        2
18  1.540435  b      5     high        2
19 -1.668788  b      1      low        1

In [184]:
Q1 = np.percentile(df["C1"], 25)  # 1사분위수(25%)
Q3 = np.percentile(df["C1"], 75)  # 3사분위수(25%)

# IQR = Q3 - Q1
# outlier 경계선
# Q3 + IQR*1.5
# Q1 - IQR*1.5

-2.9770687661990136

In [186]:
# np.where 안에 거짓 부분에 조건을 한번 더 넣어줘서 이중 if 문 처럼 만들 수 있다.

df["high_med_low"] = np.where(df["C1"]<Q1, "low",np.where(df["C1"]<Q3, "med", "high"))
df

C1 C2  C1bin high_low  highLow high_med_low
0   0.256565  a      3     high        2          med
1   0.371152  a      3     high        2          med
2  -1.225436  a      1      low        1          low
3  -0.161624  a      2     high        2          med
4  -0.548289  a      2      low        1          med
5  -0.106206  a      2     high        2          med
6   1.418957  a      4     high        2         high
7  -0.945064  a      1      low        1          med
8  -1.024221  a      1      low        1          low
9  -0.315997  a      2      low        1          med
10 -1.600255  b      1      low        1          low
11  0.747238  b      4     high        2         high
12 -0.509416  b      2      low        1          med
13 -0.052110  b      3     high        2          med
14  0.416724  b      3     high        2         high
15  0.354600  b      3     high        2          med
16 -1.088409  b      1      low        1          low
17  0.393040  b      3     high        2         high
18  1.540435  b      5     high        2         high
19 -1.668788  b      1      low        1          low

In [190]:
pew = pd.read_csv("ds_day11_data/data/pew.csv")
pew

religion  <$10k  $10-20k  $20-30k  $30-40k  $40-50k  \
0                  Agnostic     27       34       60       81       76   
1                   Atheist     12       27       37       52       35   
2                  Buddhist     27       21       30       34       33   
3                  Catholic    418      617      732      670      638   
4        Don’t know/refused     15       14       15       11       10   
5          Evangelical Prot    575      869     1064      982      881   
6                     Hindu      1        9        7        9       11   
7   Historically Black Prot    228      244      236      238      197   
8         Jehovah's Witness     20       27       24       24       21   
9                    Jewish     19       19       25       25       30   
10            Mainline Prot    289      495      619      655      651   
11                   Mormon     29       40       48       51       56   
12                   Muslim      6        7        9       10        9   
13                 Orthodox     13       17       23       32       32   
14          Other Christian      9        7       11       13       13   
15             Other Faiths     20       33       40       46       49   
16    Other World Religions      5        2        3        4        2   
17             Unaffiliated    217      299      374      365      341   

    $50-75k  $75-100k  $100-150k  >150k  Don't know/refused  
0       137       122        109     84                  96  
1        70        73         59     74                  76  
2        58        62         39     53                  54  
3      1116       949        792    633                1489  
4        35        21         17     18                 116  
5      1486       949        723    414                1529  
6        34        47         48     54                  37  
7       223       131         81     78                 339  
8        30        15         11      6                  37  
9        95        69         87    151                 162  
10     1107       939        753    634                1328  
11      112        85         49     42                  69  
12       23        16          8      6                  22  
13       47        38         42     46                  73  
14       14        18         14     12                  18  
15       63        46         40     41                  71  
16        7         3          4      4                   8  
17      528       407        321    258                 597

In [193]:
# 데이터 구조 변경 : 피봇테이블, 스택/언스택, 멜트(melt)

In [195]:
data = pd.DataFrame({'c_ID' : ['C_001', 'C_001', 'C_002', 'C_002'],
'p_CD' : ['P_001', 'P_002', 'P_001', 'P_002'],
'p_cnt' : [1, 2, 3, 4],
'p_amt' : [100, 200, 300, 400]})
data

c_ID   p_CD  p_cnt  p_amt
0  C_001  P_001      1    100
1  C_001  P_002      2    200
2  C_002  P_001      3    300
3  C_002  P_002      4    400

In [196]:
help(pd.melt)

Help on function melt in module pandas.core.reshape.melt:

melt(frame: 'DataFrame', id_vars=None, value_vars=None, var_name=None, value_name='value', col_level=None, ignore_index: bool = True) -> 'DataFrame'
    Unpivot a DataFrame from wide to long format, optionally leaving identifiers set.
    
    This function is useful to massage a DataFrame into a format where one
    or more columns are identifier variables (`id_vars`), while all other
    columns, considered measured variables (`value_vars`), are "unpivoted" to
    the row axis, leaving just two non-identifier columns, 'variable' and
    'value'.
    
    Parameters
    ----------
    id_vars : tuple, list, or ndarray, optional
        Column(s) to use as identifier variables.
    value_vars : tuple, list, or ndarray, optional
        Column(s) to unpivot. If not specified, uses all columns that
        are not set as `id_vars`.
    var_name : scalar
        Name to use for the 'variable' column. If None it uses
        ``fram

In [198]:
data

c_ID   p_CD  p_cnt  p_amt
0  C_001  P_001      1    100
1  C_001  P_002      2    200
2  C_002  P_001      3    300
3  C_002  P_002      4    400

In [210]:
pd.melt(data,id_vars=["c_ID","p_CD"])

c_ID   p_CD variable  value
0  C_001  P_001    p_cnt      1
1  C_001  P_002    p_cnt      2
2  C_002  P_001    p_cnt      3
3  C_002  P_002    p_cnt      4
4  C_001  P_001    p_amt    100
5  C_001  P_002    p_amt    200
6  C_002  P_001    p_amt    300
7  C_002  P_002    p_amt    400

In [201]:
pd.melt(data,id_vars=["c_ID","p_CD"], var_name="pch_cd",value_name="pch_value")

# id_vars : 그 컬럼은 살려둬라
# variable : 나머지 컬럼의 이름이 들어감
# value : 그 컬럼에 해당됐던 값(value) 가 들어감

c_ID   p_CD pch_cd  pch_value
0  C_001  P_001  p_cnt          1
1  C_001  P_002  p_cnt          2
2  C_002  P_001  p_cnt          3
3  C_002  P_002  p_cnt          4
4  C_001  P_001  p_amt        100
5  C_001  P_002  p_amt        200
6  C_002  P_001  p_amt        300
7  C_002  P_002  p_amt        400

In [206]:
data

c_ID   p_CD  p_cnt  p_amt
0  C_001  P_001      1    100
1  C_001  P_002      2    200
2  C_002  P_001      3    300
3  C_002  P_002      4    400

In [213]:
data_melt = pd.melt(data, id_vars=['c_ID', 'p_CD'], var_name='pch_cd', value_name='pch_value')
data_melt
# melt된 데이터는 0번부터 행 index 번호가 부여됨

c_ID   p_CD pch_cd  pch_value
0  C_001  P_001  p_cnt          1
1  C_001  P_002  p_cnt          2
2  C_002  P_001  p_cnt          3
3  C_002  P_002  p_cnt          4
4  C_001  P_001  p_amt        100
5  C_001  P_002  p_amt        200
6  C_002  P_001  p_amt        300
7  C_002  P_002  p_amt        400

In [215]:
data_melt.index
data_melt.columns
# melt된 데이터는 0번부터 행 index 번호가 부여됨

Index(['c_ID', 'p_CD', 'pch_cd', 'pch_value'], dtype='object')

In [243]:
pd.pivot_table(data_melt, index = ["c_ID","p_CD"], columns = 'pch_cd',values = 'pch_value')

pch_cd       p_amt  p_cnt
c_ID  p_CD               
C_001 P_001    100      1
      P_002    200      2
C_002 P_001    300      3
      P_002    400      4

In [244]:
pew

religion  <$10k  $10-20k  $20-30k  $30-40k  $40-50k  \
0                  Agnostic     27       34       60       81       76   
1                   Atheist     12       27       37       52       35   
2                  Buddhist     27       21       30       34       33   
3                  Catholic    418      617      732      670      638   
4        Don’t know/refused     15       14       15       11       10   
5          Evangelical Prot    575      869     1064      982      881   
6                     Hindu      1        9        7        9       11   
7   Historically Black Prot    228      244      236      238      197   
8         Jehovah's Witness     20       27       24       24       21   
9                    Jewish     19       19       25       25       30   
10            Mainline Prot    289      495      619      655      651   
11                   Mormon     29       40       48       51       56   
12                   Muslim      6        7        9       10        9   
13                 Orthodox     13       17       23       32       32   
14          Other Christian      9        7       11       13       13   
15             Other Faiths     20       33       40       46       49   
16    Other World Religions      5        2        3        4        2   
17             Unaffiliated    217      299      374      365      341   

    $50-75k  $75-100k  $100-150k  >150k  Don't know/refused  
0       137       122        109     84                  96  
1        70        73         59     74                  76  
2        58        62         39     53                  54  
3      1116       949        792    633                1489  
4        35        21         17     18                 116  
5      1486       949        723    414                1529  
6        34        47         48     54                  37  
7       223       131         81     78                 339  
8        30        15         11      6                  37  
9        95        69         87    151                 162  
10     1107       939        753    634                1328  
11      112        85         49     42                  69  
12       23        16          8      6                  22  
13       47        38         42     46                  73  
14       14        18         14     12                  18  
15       63        46         40     41                  71  
16        7         3          4      4                   8  
17      528       407        321    258                 597

In [249]:
pew.keys()[1:]

Index(['<$10k', '$10-20k', '$20-30k', '$30-40k', '$40-50k', '$50-75k',
       '$75-100k', '$100-150k', '>150k', 'Don't know/refused'],
      dtype='object')

In [252]:
pew.melt(id_vars=["religion"],
         var_name="income",
         value_name="count")

religion              income  count
0                 Agnostic               <$10k     27
1                  Atheist               <$10k     12
2                 Buddhist               <$10k     27
3                 Catholic               <$10k    418
4       Don’t know/refused               <$10k     15
..                     ...                 ...    ...
175               Orthodox  Don't know/refused     73
176        Other Christian  Don't know/refused     18
177           Other Faiths  Don't know/refused     71
178  Other World Religions  Don't know/refused      8
179           Unaffiliated  Don't know/refused    597

[180 rows x 3 columns]

In [254]:
billboard = pd.read_csv("ds_day11_data/data/billboard.csv")
billboard

year            artist                    track  time date.entered  wk1  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   87   
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02   91   
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08   81   
3    2000      3 Doors Down                    Loser  4:24   2000-10-21   76   
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15   57   
..    ...               ...                      ...   ...          ...  ...   
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29   86   
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01   85   
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18   95   
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02   99   
316  2000   matchbox twenty                     Bent  4:12   2000-04-29   60   

      wk2   wk3   wk4   wk5  ...  wk67  wk68  wk69  wk70  wk71  wk72  wk73  \
0    82.0  72.0  77.0  87.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
1    87.0  92.0   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
2    70.0  68.0  67.0  66.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3    76.0  72.0  69.0  67.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4    34.0  25.0  17.0  17.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
..    ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...   ...   
312  83.0  77.0  74.0  83.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
313  83.0  83.0  82.0  81.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
314  94.0  91.0  85.0  84.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
315  99.0   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
316  37.0  29.0  24.0  22.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

     wk74  wk75  wk76  
0     NaN   NaN   NaN  
1     NaN   NaN   NaN  
2     NaN   NaN   NaN  
3     NaN   NaN   NaN  
4     NaN   NaN   NaN  
..    ...   ...   ...  
312   NaN   NaN   NaN  
313   NaN   NaN   NaN  
314   NaN   NaN   NaN  
315   NaN   NaN   NaN  
316   NaN   NaN   NaN  

[317 rows x 81 columns]

In [256]:
billboard.melt(id_vars=billboard.keys()[:5],
               var_name="week",
               value_name="rating")

year            artist                    track  time date.entered  \
0      2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   
1      2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02   
2      2000      3 Doors Down               Kryptonite  3:53   2000-04-08   
3      2000      3 Doors Down                    Loser  4:24   2000-10-21   
4      2000          504 Boyz            Wobble Wobble  3:35   2000-04-15   
...     ...               ...                      ...   ...          ...   
24087  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29   
24088  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01   
24089  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18   
24090  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02   
24091  2000   matchbox twenty                     Bent  4:12   2000-04-29   

       week  rating  
0       wk1    87.0  
1       wk1    91.0  
2       wk1    81.0  
3       wk1    76.0  
4       wk1    57.0  
...     ...     ...  
24087  wk76     NaN  
24088  wk76     NaN  
24089  wk76     NaN  
24090  wk76     NaN  
24091  wk76     NaN  

[24092 rows x 7 columns]